
[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "Code ğŸ’»"
path = "~/Projects"
startup_command = "l"

[[session]]
name = "GitHub ğŸ’»"
path = "~/Projects/GitHub/"
startup_command = "l"

[[session]]
name = "Clients ğŸ’»"
path = "~/Projects/Clients"
startup_command = "l"

[[session]]
name = "tmux config ğŸªŸ"
path = "~/dotfiles/tmux"
startup_command = "nvim .config/tmux/tmux.conf"

[[session]]
name = "wezterm config ğŸŒŒ"
path = "~/dotfiles/wezterm"
startup_command = "nvim .config/wezterm/wezterm.lua"

[[session]]
name = "sesh config ğŸŒŒ"
path = "~/dotfiles/tmux/"
startup_command = "nvim .config/sesh/sesh.toml"

[[session]]
name = "dotfiles ğŸ”§"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"
