k9s:
  # Enable periodic refresh of resource browser windows. Default false
  liveViewAutoRefresh: false
  # Represents ui poll intervals. Default 2secs
  refreshRate: 2
  # Number of retries once the connection to the api-server is lost. Default 15.
  maxConnRetry: 15
  # Specifies if modification commands like delete/kill/edit are disabled. Default is false
  readOnly: false
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exist k9s via the :quit command. Default is false.
  noExitOnCtrlC: false
  ui:
    skin: catppuccin-mocha-transparent
    # Enable mouse support. Default false
    enableMouse: true
    # Set to true to hide K9s header. Default false
    headless: false
    # Set to true to hide K9s logo. Default false
    logoless: true
    # Set to true to hide K9s crumbs. Default false
    crumbsless: false
    # Toggles reactive UI. This option provide for watching on disk artifacts changes and update the UI live  Defaults to false.
    reactive: false
    # Toggles icons display as not all terminal support these chars.
    noIcons: false
  # Toggles whether k9s should check for the latest revision from the Github repository releases. Default is false.
  skipLatestRevCheck: true
  # Disable count pods while in node view. Default is false.
  disablePodCounting: false
  # ShellPod configuration applies to all your clusters
  shellPod:
    # The shell pod image to use.
    image: busybox:1.35.0
    # The namespace to launch to shell pod into.
    namespace: default
    # The resource limit to set on the shell pod.
    limits:
      cpu: 100m
      memory: 100Mi
    # Enable TTY
    tty: true
  # ImageScan config changed from v0.29.0!
  imageScans:
    enable: false
    # Exclusions excludes namespaces or specific workload labels
    exclusions:
      # Exclude the following namespaces for image vulscans!
      namespaces:
      - kube-system
  # Logs configuration
  logger:
    # Defines the number of lines to return. Default 100
    tail: 100
    # Defines the total number of log lines to allow in the view. Default 1000
    buffer: 5000
    # Represents how far to go back in the log timeline in seconds. Setting to -1 will tail logs. Default is -1.
    sinceSeconds: 300
    # Go full screen while displaying logs. Default false
    fullScreen: false
    # Toggles log line wrap. Default false
    textWrap: false
    # Toggles log line timestamp info. Default false
    showTime: false
  # Global memory/cpu thresholds. When set will alert when thresholds are met.
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70